### ISSUE TITLE
Lutris not launching on new install of Pop!_OS 20.10

### ISSUE THREAD

**Issue by DankeBrutus** [lutris/docs#49]
I have used Lutris no problem on Manjaro, Feren, and a previous install of Pop but this time Lutris will not launch. I have tried installing through the Pop Shop and through the regular 'sudo apt install lutris' command in terminal. Launching Lutris via terminal gives me this...

`Traceback (most recent call last):
  File "/usr/games/lutris", line 54, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/lutris/gui/application.py", line 53, in <module>
    from .lutriswindow import LutrisWindow
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 26, in <module>
    from lutris.gui.widgets.sidebar import LutrisSidebar
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/sidebar.py", line 6, in <module>
    from lutris import platforms, runners, services
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 19, in <module>
    _init_platforms()
  File "/usr/lib/python3/dist-packages/lutris/platforms.py", line 14, in _init_platforms
    runner = runners.import_runner(runner_name)()
  File "/usr/lib/python3/dist-packages/lutris/runners/wine.py", line 229, in __init__
    "default": dxvk.DXVKManager().version,
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 56, in version
    return self.versions[0]
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 45, in versions
    self._versions = self.load_dxvk_versions()
  File "/usr/lib/python3/dist-packages/lutris/util/wine/dxvk.py", line 65, in load_dxvk_versions
    with open(versions_path, "r") as dxvk_version_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/adamkucharik/.local/share/lutris/runtime/dxvk/dxvk_versions.json'
`

From I can tell it seems like I am missing something that, for whatever reason, the install of Lutris did not provide. I have already enabled the repositories found here (https://github.com/lutris/docs/blob/master/WineDependencies.md) and I still get the same wall of text in terminal.

**Comment by DankeBrutus** [comment]
This seemed to fix it:
`wget  https://cdn.discordapp.com/attachments/538903130704838656/796102070825779250/dxvk_versions.json  -P $HOME/.local/share/lutris/runtime/dxvk
`
